// 샘플 시드 데이터 — 실제 공공 API 키 발급 전까지 사용
// 발급 후 lib/store.ts에서 외부 fetch로 갈아끼움
// 데이터는 실제 한국 복지·일자리 제도를 기반으로 한 사실적 시드.

import type { Job, PoomasiPost, UserProfile } from "./types";

// 가상 사용자 (서울 종로구 종로1·2·3·4가동, 만 70세, 1인 가구)
export const sampleUser: UserProfile = {
  id: "u-demo-001",
  name: "김정숙",
  birthYear: 1956,
  dongCode: "1111051500",
  dongName: "종로구 종로1·2·3·4가동",
  household: "single",
  householdSize: 1,
  monthlyIncomeKrw: 600_000, // 월 60만원 — 기초연금 34만원 + 노인일자리 27만원 가정
  pensionStatus: "receiving",
  interests: ["문화", "산책", "한글교실"],
  lat: 37.5703,
  lng: 126.9824,
  region: "서울특별시",
  district: "종로구",
  welfareStatus: "unknown", // 자동 통과 방지 — 매처가 실제 소득 기준으로 검사하도록
  hasDisability: false,
  healthConcerns: ["eyes", "teeth"],
  housingType: "monthly_rent",
  delinquencies: ["utility"],
  citizenship: "KR",
  // 김정숙님이 이미 신청·수령 중인 혜택 (시연용)
  receivedBenefitIds: [
    "basic-pension",       // 기초연금
    "telecom-discount",    // 통신비 감면
    "transport-card",      // 지하철 경로 무임
    "tv-license-exempt",   // TV 수신료 면제
  ],
  jobPreferences: {
    preferredJobTypes: ["사회서비스형", "공익활동형"],
    pastOccupations: ["교육보조", "주민자치"],
    maxCommuteMinutes: 30,
    preferredTimeSlots: ["morning"],
    desiredHourlyWageKrw: 9620,
    outdoorOk: false,
    walkingHeavyOk: true,
    drivingOk: false,
  },
};

// ─────────────────────────────────────────────────────────
// 복지 프로그램 (편집본 22건)
// ─────────────────────────────────────────────────────────

export const sampleWelfarePrograms: WelfareProgram[] = [
  {
    id: "w-001",
    source: "복지로",
    sourceId: "BJ-PENSION-BASIC",
    title: "기초연금",
    summary:
      "만 65세 이상 · 가족 포함 월 소득 213만원 이하면 받을 수 있어요. 매달 통장으로 최대 34만원.",
    category: "cash",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: 213,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 342510,
    benefitNote: "월 최대 342,510원",
    deadline: null,
    applyUrl: "https://basicpension.mohw.go.kr",
    documents: ["주민등록등본", "통장 사본", "소득 증빙"],
    agencyHint: "관할 행정복지센터 또는 국민연금공단 지사",
  },
  {
    id: "w-002",
    source: "복지로",
    sourceId: "BJ-ENERGY-VOUCHER",
    title: "에너지 바우처 (겨울)",
    summary:
      "65세 이상 + 기초생활보장 또는 차상위라면 겨울 난방비를 지원받을 수 있어요.",
    category: "energy",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: 187,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 195000,
    benefitNote: "연 최대 195,000원",
    deadline: "2026-12-31",
    applyUrl: "https://energyv.energy.or.kr",
    documents: ["주민등록등본", "수급자 증명서"],
    agencyHint: "주민센터",
  },
  {
    id: "w-003",
    source: "공공데이터포털",
    sourceId: "MCST-CULTURE-PASS",
    title: "문화누리카드",
    summary:
      "기초생활수급자·차상위라면 연 14만원의 문화·여행·체육 바우처를 받을 수 있어요.",
    category: "culture",
    ageMin: 0,
    ageMax: 200,
    incomeMaxKrw: 187,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 140000,
    benefitNote: "연 140,000원",
    deadline: "2026-11-30",
    applyUrl: "https://www.mnuri.kr",
    documents: ["신분증"],
    agencyHint: "주민센터 또는 농협",
  },
  {
    id: "w-004",
    source: "공공데이터포털",
    sourceId: "NHIS-SCREENING",
    title: "국가건강검진",
    summary: "만 66세 이후 매 2년 무료. 종합 검진 + 인지기능 검사 포함.",
    category: "medical",
    ageMin: 66,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 0,
    benefitNote: "무료 (가치 환산 약 25만원)",
    deadline: null,
    applyUrl: "https://www.nhis.or.kr",
    documents: ["신분증"],
    agencyHint: "지정 검진기관",
  },
  {
    id: "w-005",
    source: "지자체",
    sourceId: "JONGNO-MOVE-2026",
    title: "이동지원 서비스 (종로구)",
    summary:
      "종로구 거주 만 65세 이상은 월 8회 콜택시·복지차량을 무료로 이용할 수 있어요.",
    category: "voucher",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: ["1111051500", "1111051000", "1111052000"],
    benefitAmountKrw: 80000,
    benefitNote: "월 최대 8회",
    deadline: null,
    applyUrl: "https://www.jongno.go.kr",
    documents: ["주민등록등본"],
    agencyHint: "종로구청 복지과",
  },
  {
    id: "w-006",
    source: "복지로",
    sourceId: "MOHW-SENIOR-JOB-2026",
    title: "노인일자리 사업 (2026 상반기)",
    summary:
      "만 65세 이상이면 공공·사회서비스형 일자리에 신청할 수 있어요. 월 27만원 안팎 활동비 지급.",
    category: "job",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 271000,
    benefitNote: "월 약 271,000원",
    deadline: "2026-05-31",
    applyUrl: "https://www.seniorro.or.kr",
    documents: ["주민등록등본", "통장 사본"],
    agencyHint: "동 주민센터 또는 시니어클럽",
  },
  {
    id: "w-007",
    source: "복지로",
    sourceId: "BJ-LONGTERM-CARE",
    title: "장기요양보험",
    summary: "일상생활이 힘드시면 등급 신청을 통해 방문요양·주야간보호 서비스를 받을 수 있어요.",
    category: "medical",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 1500000,
    benefitNote: "월 최대 약 150만원 한도",
    deadline: null,
    applyUrl: "https://www.longtermcare.or.kr",
    documents: ["주민등록등본", "의사 소견서"],
    agencyHint: "국민건강보험공단 장기요양",
  },
  {
    id: "w-008",
    source: "복지로",
    sourceId: "BJ-EYEGLASS-2026",
    title: "노인 안경 지원 (종로구)",
    summary: "만 65세 이상 종로구 거주 어르신께 연 1회 안경 교체비 10만원 지원.",
    category: "medical",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: ["1111051500", "1111051000", "1111052000"],
    benefitAmountKrw: 100000,
    benefitNote: "연 100,000원",
    deadline: "2026-09-30",
    applyUrl: "https://www.jongno.go.kr",
    documents: ["주민등록등본", "안경 영수증"],
    agencyHint: "종로구청 노인복지과",
  },
  {
    id: "w-009",
    source: "복지로",
    sourceId: "BJ-FREE-LUNCH",
    title: "경로식당 무료 점심",
    summary: "관내 경로식당에서 평일 점심을 무료로 드실 수 있어요. 저소득 어르신 우선.",
    category: "voucher",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: 150,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 132000,
    benefitNote: "월 약 132,000원 식비 가치",
    deadline: null,
    applyUrl: "https://www.bokjiro.go.kr",
    documents: ["주민등록등본", "수급 증빙(있는 경우)"],
    agencyHint: "관할 노인복지관",
  },
  {
    id: "w-010",
    source: "복지로",
    sourceId: "BJ-FREE-METRO",
    title: "지하철 경로 무임승차",
    summary: "만 65세 이상은 수도권 지하철·일부 광역철도를 무료로 이용할 수 있어요.",
    category: "voucher",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 60000,
    benefitNote: "월 약 60,000원 가치",
    deadline: null,
    applyUrl: "https://www.smrt.co.kr",
    documents: ["주민등록증"],
    agencyHint: "지하철 역 매표소",
  },
  {
    id: "w-011",
    source: "지자체",
    sourceId: "SEOUL-DENTAL-2026",
    title: "어르신 무료 임플란트 (서울)",
    summary: "만 65세 이상 건강보험 가입자는 평생 2개까지 임플란트를 30% 본인부담으로 받을 수 있어요.",
    category: "medical",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 800000,
    benefitNote: "1개당 약 80만원 절감",
    deadline: null,
    applyUrl: "https://www.nhis.or.kr",
    documents: ["건강보험증"],
    agencyHint: "지정 치과",
  },
  {
    id: "w-012",
    source: "복지로",
    sourceId: "BJ-PHONE-SUBSIDY",
    title: "어르신 통신요금 감면",
    summary: "기초연금 수급자라면 휴대전화·인터넷 요금을 월 11,000원까지 감면받을 수 있어요.",
    category: "cash",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: 213,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 132000,
    benefitNote: "연 132,000원",
    deadline: null,
    applyUrl: "https://www.msit.go.kr",
    documents: ["기초연금 수급 증명"],
    agencyHint: "통신사 대리점",
  },
  {
    id: "w-013",
    source: "지자체",
    sourceId: "JONGNO-HEAT-2026",
    title: "쪽방·반지하 냉방 지원 (종로구)",
    summary: "여름철 냉방비 부담을 덜기 위해 종로구 거주 저소득 어르신께 7~8월 전기료 지원.",
    category: "energy",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: 150,
    householdAllowed: [],
    regionCodes: ["1111051500", "1111051000", "1111052000"],
    benefitAmountKrw: 100000,
    benefitNote: "여름 100,000원",
    deadline: "2026-06-30",
    applyUrl: "https://www.jongno.go.kr",
    documents: ["주민등록등본", "수급 증빙"],
    agencyHint: "동 주민센터",
  },
  {
    id: "w-014",
    source: "복지로",
    sourceId: "BJ-FUNERAL",
    title: "장제급여",
    summary: "기초생활수급자 가구의 장례 비용 일부를 정부가 지원해드려요.",
    category: "cash",
    ageMin: 0,
    ageMax: 200,
    incomeMaxKrw: 100,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 800000,
    benefitNote: "1회 800,000원",
    deadline: null,
    applyUrl: "https://www.bokjiro.go.kr",
    documents: ["사망진단서", "수급 증빙"],
    agencyHint: "주민센터",
  },
  {
    id: "w-015",
    source: "복지로",
    sourceId: "BJ-WALK-AID",
    title: "보행보조기·휠체어 대여",
    summary: "장기요양 등급 미신청자도 단기 보행 어려움이 있을 때 보행보조기를 빌릴 수 있어요.",
    category: "medical",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 60000,
    benefitNote: "월 약 60,000원 가치",
    deadline: null,
    applyUrl: "https://www.bokjiro.go.kr",
    documents: ["신분증"],
    agencyHint: "보건소·복지관",
  },
  {
    id: "w-016",
    source: "지자체",
    sourceId: "JONGNO-DIGITAL-EDU",
    title: "디지털 교육 (종로구)",
    summary: "스마트폰·키오스크·AI 챗봇 사용법을 배울 수 있는 무료 강좌. 매주 수요일.",
    category: "culture",
    ageMin: 60,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: ["1111051500", "1111051000"],
    benefitAmountKrw: 0,
    benefitNote: "무료 강좌",
    deadline: "2026-06-15",
    applyUrl: "https://www.jongno.go.kr",
    documents: ["주민등록등본"],
    agencyHint: "종로구청 평생학습관",
  },
  {
    id: "w-017",
    source: "복지로",
    sourceId: "BJ-EMERGENCY-CARE",
    title: "응급안전 안심서비스",
    summary: "독거 어르신 댁에 응급버튼·화재감지기 무료 설치 + 24시간 상황실 모니터링.",
    category: "medical",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: ["single"],
    regionCodes: [],
    benefitAmountKrw: 200000,
    benefitNote: "설치 가치 약 200,000원",
    deadline: null,
    applyUrl: "https://www.bokjiro.go.kr",
    documents: ["주민등록등본"],
    agencyHint: "지역 노인복지관",
  },
  {
    id: "w-018",
    source: "복지로",
    sourceId: "BJ-SOLO-MEAL",
    title: "독거노인 도시락 배달",
    summary: "혼자 사시는 어르신께 평일 점심 도시락을 댁으로 배달해드려요.",
    category: "voucher",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: 150,
    householdAllowed: ["single"],
    regionCodes: [],
    benefitAmountKrw: 132000,
    benefitNote: "월 약 132,000원",
    deadline: null,
    applyUrl: "https://www.bokjiro.go.kr",
    documents: ["주민등록등본", "단독세대 확인"],
    agencyHint: "관할 노인복지관",
  },
  {
    id: "w-019",
    source: "복지로",
    sourceId: "BJ-HOUSING-REPAIR",
    title: "어르신 집수리 지원",
    summary: "낡은 집을 안전하게 수리하실 수 있게 1회 최대 380만원까지 지원합니다.",
    category: "housing",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: 187,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 3800000,
    benefitNote: "1회 최대 380만원",
    deadline: "2026-08-31",
    applyUrl: "https://www.bokjiro.go.kr",
    documents: ["주민등록등본", "주택 소유 또는 임대 증빙"],
    agencyHint: "주민센터·LH",
  },
  {
    id: "w-020",
    source: "복지로",
    sourceId: "BJ-DEMENTIA-CHECK",
    title: "치매 무료 조기 검진",
    summary: "치매안심센터에서 인지기능 검사를 무료로 받을 수 있어요. 검사 후 인지 훈련 프로그램 연결.",
    category: "medical",
    ageMin: 60,
    ageMax: 200,
    incomeMaxKrw: null,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 50000,
    benefitNote: "무료 (가치 약 50,000원)",
    deadline: null,
    applyUrl: "https://www.nid.or.kr",
    documents: ["신분증"],
    agencyHint: "보건소 치매안심센터",
  },
  {
    id: "w-021",
    source: "지자체",
    sourceId: "JONGNO-FUNERAL-SUP",
    title: "가족돌봄 휴직 지원금",
    summary: "부모·배우자를 돌보기 위해 휴직한 50세 이상 종로구민에게 월 50만원 지원.",
    category: "cash",
    ageMin: 50,
    ageMax: 200,
    incomeMaxKrw: 250,
    householdAllowed: [],
    regionCodes: ["1111051500", "1111051000", "1111052000"],
    benefitAmountKrw: 500000,
    benefitNote: "월 500,000원 (최대 6개월)",
    deadline: "2026-12-31",
    applyUrl: "https://www.jongno.go.kr",
    documents: ["가족관계증명서", "휴직증명서"],
    agencyHint: "종로구청 일자리경제과",
  },
  {
    id: "w-022",
    source: "복지로",
    sourceId: "BJ-NUTRITION-2026",
    title: "노인 영양보충 식품 지원",
    summary: "저소득 어르신께 분기마다 영양식·우유·계란 등 식료품 꾸러미를 보내드려요.",
    category: "voucher",
    ageMin: 65,
    ageMax: 200,
    incomeMaxKrw: 150,
    householdAllowed: [],
    regionCodes: [],
    benefitAmountKrw: 60000,
    benefitNote: "분기당 60,000원 상당",
    deadline: null,
    applyUrl: "https://www.bokjiro.go.kr",
    documents: ["주민등록등본", "수급 증빙"],
    agencyHint: "주민센터",
  },
];

// ─────────────────────────────────────────────────────────
// 일자리 (서울 종로 근처 + 인접 지역, 14건)
// ─────────────────────────────────────────────────────────

export const sampleJobs: Job[] = [
  {
    id: "j-001",
    source: "워크넷",
    sourceId: "WORK-2026-3401",
    title: "초등학교 학습보조 도우미",
    org: "종로 시니어클럽",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.572,
    lng: 126.985,
    jobTags: ["교육", "학습보조"],
    activityType: "사회서비스형",
    difficulty: "low",
    outdoor: false,
    walkingHeavy: false,
    drivingRequired: false,
    ageMin: 65,
    agePreferred: 70,
    wageKrwPerHour: 9620,
    hoursPerWeek: 10,
    timeSlot: "morning",
    schedule: "월·수·금 오전 9시~12시",
    requirements: ["만 65세 이상", "보호자 동의"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-720-1234",
    expiresAt: "2026-05-25T23:59:59Z",
  },
  {
    id: "j-002",
    source: "워크넷",
    sourceId: "WORK-2026-3415",
    title: "공원 환경 지킴이",
    org: "종로구청 일자리",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.5705,
    lng: 126.9899,
    jobTags: ["환경", "공원정비"],
    activityType: "공익활동형",
    difficulty: "mid",
    outdoor: true,
    walkingHeavy: true,
    drivingRequired: false,
    ageMin: 65,
    agePreferred: null,
    wageKrwPerHour: 9620,
    hoursPerWeek: 6,
    timeSlot: "morning",
    schedule: "주 3회 오전 7시~9시",
    requirements: ["만 65세 이상", "야외활동 가능"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-720-5678",
    expiresAt: "2026-05-20T23:59:59Z",
  },
  {
    id: "j-003",
    source: "지자체수행기관",
    sourceId: "JONGNO-LIB-2026",
    title: "도서관 책 정리 도우미",
    org: "종로도서관",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.5732,
    lng: 126.9848,
    jobTags: ["문화", "도서관"],
    activityType: "사회서비스형",
    difficulty: "low",
    outdoor: false,
    walkingHeavy: true,
    drivingRequired: false,
    ageMin: 60,
    agePreferred: null,
    wageKrwPerHour: 10000,
    hoursPerWeek: 8,
    timeSlot: "afternoon",
    schedule: "화·목 오후 1시~5시",
    requirements: ["책 분류 가능", "주 2회 출근"],
    applyUrl: "https://lib.jongno.go.kr",
    contactPhone: "02-721-2222",
    expiresAt: "2026-06-10T23:59:59Z",
  },
  {
    id: "j-004",
    source: "워크넷",
    sourceId: "WORK-2026-3491",
    title: "지하철 안내 도우미",
    org: "서울교통공사 협력",
    regionCode: "1111051000",
    regionName: "종로구 청운효자동",
    lat: 37.5825,
    lng: 126.9698,
    jobTags: ["교통", "응대"],
    activityType: "공익활동형",
    difficulty: "mid",
    outdoor: false,
    walkingHeavy: true,
    drivingRequired: false,
    ageMin: 65,
    agePreferred: null,
    wageKrwPerHour: 9620,
    hoursPerWeek: 10,
    timeSlot: "morning",
    schedule: "월~금 중 3일 · 오전",
    requirements: ["만 65세 이상", "응대 가능"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-720-9999",
    expiresAt: "2026-05-30T23:59:59Z",
  },
  {
    id: "j-005",
    source: "워크넷",
    sourceId: "WORK-2026-3502",
    title: "주민센터 안내 도우미",
    org: "종로구청",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.5715,
    lng: 126.9837,
    jobTags: ["행정", "응대"],
    activityType: "사회서비스형",
    difficulty: "low",
    outdoor: false,
    walkingHeavy: false,
    drivingRequired: false,
    ageMin: 60,
    agePreferred: 65,
    wageKrwPerHour: 11000,
    hoursPerWeek: 12,
    timeSlot: "morning",
    schedule: "월·화·수·목 오전 9~12시",
    requirements: ["응대 가능", "기본 컴퓨터"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-720-2020",
    expiresAt: "2026-06-15T23:59:59Z",
  },
  {
    id: "j-006",
    source: "워크넷",
    sourceId: "WORK-2026-3601",
    title: "어린이집 등하원 안전 도우미",
    org: "종로구 보육사업단",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.5688,
    lng: 126.985,
    jobTags: ["보육", "교통안전"],
    activityType: "사회서비스형",
    difficulty: "mid",
    outdoor: true,
    walkingHeavy: true,
    drivingRequired: false,
    ageMin: 60,
    agePreferred: 65,
    wageKrwPerHour: 10500,
    hoursPerWeek: 10,
    timeSlot: "morning",
    schedule: "월~금 오전 8~10시",
    requirements: ["보육 경험 우대"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-720-3030",
    expiresAt: "2026-06-20T23:59:59Z",
  },
  {
    id: "j-007",
    source: "지자체수행기관",
    sourceId: "JONGNO-CULTURE-DOCENT",
    title: "박물관 시니어 해설사",
    org: "서울역사박물관",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.571,
    lng: 126.97,
    jobTags: ["문화", "해설"],
    activityType: "사회서비스형",
    difficulty: "low",
    outdoor: false,
    walkingHeavy: true,
    drivingRequired: false,
    ageMin: 60,
    agePreferred: null,
    wageKrwPerHour: 12000,
    hoursPerWeek: 8,
    timeSlot: "afternoon",
    schedule: "수·금 오후 1~5시",
    requirements: ["역사·문화 관심", "사전교육 이수"],
    applyUrl: "https://www.museum.seoul.go.kr",
    contactPhone: "02-724-0114",
    expiresAt: "2026-07-10T23:59:59Z",
  },
  {
    id: "j-008",
    source: "워크넷",
    sourceId: "WORK-2026-3722",
    title: "스쿨존 교통 정리",
    org: "종로구 시설관리공단",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.575,
    lng: 126.99,
    jobTags: ["교통안전", "공원정비"],
    activityType: "공익활동형",
    difficulty: "mid",
    outdoor: true,
    walkingHeavy: true,
    drivingRequired: false,
    ageMin: 65,
    agePreferred: null,
    wageKrwPerHour: 9620,
    hoursPerWeek: 10,
    timeSlot: "morning",
    schedule: "주 5회 오전 7~9시",
    requirements: ["야외활동 가능"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-720-7070",
    expiresAt: "2026-05-22T23:59:59Z",
  },
  {
    id: "j-009",
    source: "워크넷",
    sourceId: "WORK-2026-3801",
    title: "공방 보조 (목공·도자기)",
    org: "북촌공방협회",
    regionCode: "1111052000",
    regionName: "종로구 가회동",
    lat: 37.582,
    lng: 126.985,
    jobTags: ["문화", "공예"],
    activityType: "시장형",
    difficulty: "mid",
    outdoor: false,
    walkingHeavy: false,
    drivingRequired: false,
    ageMin: 55,
    agePreferred: null,
    wageKrwPerHour: 13000,
    hoursPerWeek: 16,
    timeSlot: "afternoon",
    schedule: "주 4회 오후",
    requirements: ["공예 경험 우대"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-742-1111",
    expiresAt: "2026-06-30T23:59:59Z",
  },
  {
    id: "j-010",
    source: "지자체수행기관",
    sourceId: "JONGNO-COMM-CARE",
    title: "독거 어르신 안부 전화",
    org: "종로노인종합복지관",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.572,
    lng: 126.987,
    jobTags: ["사회복지", "응대"],
    activityType: "사회서비스형",
    difficulty: "low",
    outdoor: false,
    walkingHeavy: false,
    drivingRequired: false,
    ageMin: 60,
    agePreferred: null,
    wageKrwPerHour: 11500,
    hoursPerWeek: 8,
    timeSlot: "morning",
    schedule: "월·수·금 오전",
    requirements: ["대화 응대 가능"],
    applyUrl: "https://jongno-senior.or.kr",
    contactPhone: "02-733-0707",
    expiresAt: "2026-07-01T23:59:59Z",
  },
  {
    id: "j-011",
    source: "워크넷",
    sourceId: "WORK-2026-3950",
    title: "복지관 식당 보조",
    org: "종로노인종합복지관",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.572,
    lng: 126.987,
    jobTags: ["식당", "주방"],
    activityType: "사회서비스형",
    difficulty: "mid",
    outdoor: false,
    walkingHeavy: true,
    drivingRequired: false,
    ageMin: 60,
    agePreferred: null,
    wageKrwPerHour: 10000,
    hoursPerWeek: 15,
    timeSlot: "morning",
    schedule: "월~금 오전 10~13시",
    requirements: ["주방 위생 교육 이수 가능"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-733-1212",
    expiresAt: "2026-06-25T23:59:59Z",
  },
  {
    id: "j-012",
    source: "워크넷",
    sourceId: "WORK-2026-4011",
    title: "택배 분류 도우미 (시간제)",
    org: "협동물류조합",
    regionCode: "1111052000",
    regionName: "종로구 가회동",
    lat: 37.583,
    lng: 126.99,
    jobTags: ["물류"],
    activityType: "시장형",
    difficulty: "high",
    outdoor: false,
    walkingHeavy: true,
    drivingRequired: false,
    ageMin: 55,
    agePreferred: null,
    wageKrwPerHour: 12500,
    hoursPerWeek: 20,
    timeSlot: "evening",
    schedule: "주 5회 저녁 6~10시",
    requirements: ["체력 양호"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-744-0808",
    expiresAt: "2026-07-15T23:59:59Z",
  },
  {
    id: "j-013",
    source: "지자체수행기관",
    sourceId: "JONGNO-DIGITAL-MENTOR",
    title: "스마트폰 가르치기 멘토",
    org: "종로구 디지털배움터",
    regionCode: "1111051500",
    regionName: "종로구 종로1·2·3·4가동",
    lat: 37.5715,
    lng: 126.9837,
    jobTags: ["교육", "디지털"],
    activityType: "사회서비스형",
    difficulty: "low",
    outdoor: false,
    walkingHeavy: false,
    drivingRequired: false,
    ageMin: 60,
    agePreferred: null,
    wageKrwPerHour: 13000,
    hoursPerWeek: 10,
    timeSlot: "afternoon",
    schedule: "수·금 오후",
    requirements: ["스마트폰 사용 능숙", "교육 경험 우대"],
    applyUrl: "https://www.jongno.go.kr",
    contactPhone: "02-720-4040",
    expiresAt: "2026-07-20T23:59:59Z",
  },
  {
    id: "j-014",
    source: "워크넷",
    sourceId: "WORK-2026-4123",
    title: "공동작업장 — 천연비누 포장",
    org: "종로 시니어 공동작업장",
    regionCode: "1111052000",
    regionName: "종로구 가회동",
    lat: 37.585,
    lng: 126.989,
    jobTags: ["수공예", "포장"],
    activityType: "시장형",
    difficulty: "low",
    outdoor: false,
    walkingHeavy: false,
    drivingRequired: false,
    ageMin: 60,
    agePreferred: null,
    wageKrwPerHour: 11000,
    hoursPerWeek: 18,
    timeSlot: "morning",
    schedule: "월~금 오전",
    requirements: ["손작업 가능"],
    applyUrl: "https://www.work.go.kr",
    contactPhone: "02-741-0001",
    expiresAt: "2026-06-30T23:59:59Z",
  },
];

// ─────────────────────────────────────────────────────────
// 품앗이 게시글 (시드 콘텐츠 10건)
// ─────────────────────────────────────────────────────────

const _now = Date.now();
const _hAgo = (h: number) => new Date(_now - h * 3600 * 1000).toISOString();

export const samplePoomasiPosts: PoomasiPost[] = [
  {
    id: "p-001",
    authorId: "u-demo-002",
    authorName: "박순자",
    authorMaskedName: "박○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "life_help",
    title: "다음 주 화요일 종로보건소 같이 가실 분",
    body: "건강검진 예약했는데 혼자 가기 어려워요. 같이 가주실 분 계실까요? 마치고 점심 사드릴게요.",
    preferredTime: "5월 6일(화) 오전 10시",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(2),
  },
  {
    id: "p-002",
    authorId: "u-demo-003",
    authorName: "이복희",
    authorMaskedName: "이○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "digital",
    title: "스마트폰 문자 보내는 법 알려주세요",
    body: "딸한테 사진 보내고 싶은데 자꾸 잘못 눌러서요. 30분이면 되실 것 같아요.",
    preferredTime: "평일 오후 아무 때나",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(5),
  },
  {
    id: "p-003",
    authorId: "u-demo-004",
    authorName: "정영자",
    authorMaskedName: "정○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "talk",
    title: "낮에 산책 같이 하실 분",
    body: "혼자 걷기 심심해서요. 청계천 한 바퀴 같이 돌면 좋겠어요. 일주일에 두세 번.",
    preferredTime: "오전 10시~11시 사이",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(11),
  },
  {
    id: "p-004",
    authorId: "u-demo-005",
    authorName: "한금자",
    authorMaskedName: "한○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "house_chore",
    title: "장롱 옮기는 거 도와주실 분",
    body: "장롱 위치만 바꾸려는데 혼자 못 하겠어요. 30분이면 끝나요. 음료수 챙겨드릴게요.",
    preferredTime: "이번 주 토요일 아무 때",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(20),
  },
  {
    id: "p-005",
    authorId: "u-demo-006",
    authorName: "조춘선",
    authorMaskedName: "조○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "skill_share",
    title: "한자 가르쳐 드릴 수 있어요",
    body: "한자교실 강사 5년 했어요. 천자문 처음부터 천천히 가르쳐드릴 수 있어요. 무료.",
    preferredTime: "수·금 오전",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(28),
  },
  {
    id: "p-006",
    authorId: "u-demo-007",
    authorName: "최영애",
    authorMaskedName: "최○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "digital",
    title: "은행 앱 송금 가르쳐주세요",
    body: "공과금 내려는데 자꾸 막혀서요. 카카오뱅크 같이 봐주실 분 계세요?",
    preferredTime: "평일 오전",
    status: "matched",
    helperId: "u-demo-099",
    reportCount: 0,
    createdAt: _hAgo(36),
  },
  {
    id: "p-007",
    authorId: "u-demo-008",
    authorName: "강미란",
    authorMaskedName: "강○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "life_help",
    title: "주민센터 같이 가서 신청서 작성 도와주세요",
    body: "기초연금 신청서 어렵게 느껴져요. 같이 가서 봐주실 분 있으면 좋겠어요.",
    preferredTime: "월요일 오전",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(44),
  },
  {
    id: "p-008",
    authorId: "u-demo-009",
    authorName: "윤춘자",
    authorMaskedName: "윤○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "talk",
    title: "차 한 잔 하실 분",
    body: "오후에 동네 카페에서 차 마시며 이야기 나눌 분. 화요일·목요일 좋아요.",
    preferredTime: "화·목 오후 2~4시",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(60),
  },
  {
    id: "p-009",
    authorId: "u-demo-010",
    authorName: "오정희",
    authorMaskedName: "오○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "skill_share",
    title: "기초 영어 알려드릴게요",
    body: "영어 알파벳·인사부터 손녀와 화상통화하실 수 있게 도와드릴게요.",
    preferredTime: "주 1회 1시간",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(72),
  },
  {
    id: "p-010",
    authorId: "u-demo-011",
    authorName: "김순례",
    authorMaskedName: "김○○",
    dongCode: "1111051500",
    dongName: "종로구 종로1·2·3·4가동",
    category: "etc",
    title: "지하철 동행 — 경복궁 나들이",
    body: "혼자 가기 적적해서요. 무임승차로 같이 다녀오실 분! 점심은 각자.",
    preferredTime: "다음 주 수요일 오전",
    status: "open",
    helperId: null,
    reportCount: 0,
    createdAt: _hAgo(96),
  },
];
